# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "vendor/**/*" # rubocop config/default.yml
  DisplayCopNames: true

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/LineLength:
  Max: 120

